In [160]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets



In [161]:
iris = datasets.load_iris()
X = iris.data[:, :]  # we only take the first two features.
y = iris.target

In [162]:
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [163]:
X=X[(y==0)|(y==1)]
y=y[(y==0)|(y==1)]

In [164]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [165]:


X_train, X_test, y_train, y_test = train_test_split(X, y,
  test_size=0.25, random_state=42)

print('lets check the shape of the data')
print(X_train.shape[0],X_test.shape[0])
print('\n\n')

for i in range(5) :
    print(X_train[i,:],y_train[i])

train_size = X_train.shape[0]
test_size = X_test.shape[0]


lets check the shape of the data
75 25



[5.7 4.4 1.5 0.4] 0
[5.  3.5 1.3 0.3] 0
[5.7 2.9 4.2 1.3] 1
[4.9 3.1 1.5 0.1] 0
[6.3 2.5 4.9 1.5] 1


In [166]:

print(y_train)


[0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1
 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1 1 0 1
 1]


In [167]:
print(y_train)

[0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1
 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1 1 0 1
 1]


In [168]:
print(y_train.shape)
print(len(y_train))
y_train_copy = y_train.reshape(len(y_train),1)
print(y_train_copy.shape)

(75,)
75
(75, 1)


In [177]:
theta_array=np.zeros((X_train.shape[1],1))
theta_zero = np.zeros((1,1))
alpha = 0.0001
#print(theta_array.shape)
#print(theta_zero.shape)
#print(y_train.shape)


y_train = y_train.reshape(len(y_train),1)
#print(y_train)
#print(y_train)

for i in range(20000) :
    y_pred = np.dot(X_train,theta_array)
    
    y_pred = y_pred + theta_zero
    
    y_pred = 1/(1+np.exp(-y_pred))  
    
    train_error= y_pred - y_train
   
    #print(np.sum(-y_pred*y_train-(1-y_train)*(1-y_pred))) 
    
    theta_zero = theta_zero - alpha*(np.sum(train_error)*(1/train_size))
    #print(theta_zero.shape)
    
    for j in range(X_train.shape[1]):
        gradient = (1/train_size)*(np.dot(np.transpose(train_error),X_train[:,j]))
        theta_array[j,0]= theta_array[j,0] - alpha*gradient
        
       
        #print(theta_array)
        

In [159]:
print(y_train)

[[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]


In [179]:
y_pred = np.dot(X_test,theta_array)

y_pred = y_pred + theta_zero

y_pred = 1/(1+np.exp(-y_pred))  
print(y_pred)
y_pred = y_pred >=0.5

print(y_pred)



    






[[0.8961669 ]
 [0.82159699]
 [0.85774147]
 [0.30633995]
 [0.30532756]
 [0.27210705]
 [0.20274256]
 [0.78317762]
 [0.24118319]
 [0.25021018]
 [0.25894724]
 [0.32034376]
 [0.84598312]
 [0.19064016]
 [0.83798559]
 [0.24389641]
 [0.85350285]
 [0.87138201]
 [0.29376736]
 [0.27802162]
 [0.83679989]
 [0.78220614]
 [0.30058821]
 [0.27598012]
 [0.78578786]]
[[ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]]


In [184]:
print(np.sum(y_pred[:,0]==y_test))#acco



25
