<a href="https://colab.research.google.com/github/MehediAzim/Machine-Learning-Algorithms/blob/master/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
%cd /content/gdrive/My Drive/Pattern recognition laboratory/
!ls

/content/gdrive/My Drive/Pattern recognition laboratory
'Decision Tree'					      Lab_03-Naive_bayes.ipynb
'Decision_Tree_Classification.zip (Unzipped Files)'   Social_Network_Ads.csv
 lab02_decisionTree.ipynb			     'Untitled document.gdoc'
 Lab-03


In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = abs(sc.fit_transform(X_train))
X_test = sc.transform(X_test)
y_train = abs(y_train)

#Gaussian NB

In [ ]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB 
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
print ("Accuracy : ", 
accuracy_score(y_test,y_pred)*100) 
	
print("Report : ", 
classification_report(y_test, y_pred)) 

cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy :  78.0
Report :                precision    recall  f1-score   support

           0       0.76      1.00      0.86        68
           1       1.00      0.31      0.48        32

    accuracy                           0.78       100
   macro avg       0.88      0.66      0.67       100
weighted avg       0.83      0.78      0.74       100

[[68  0]
 [22 10]]


#NB multinomial


In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print ("Accuracy : ", 
accuracy_score(y_test,y_pred)*100) 

	
print("Report : ", 
classification_report(y_test, y_pred)) 

cm1 = confusion_matrix(y_test, y_pred)
print(cm1)

Accuracy :  69.0
Report :                precision    recall  f1-score   support

           0       0.69      1.00      0.81        68
           1       1.00      0.03      0.06        32

    accuracy                           0.69       100
   macro avg       0.84      0.52      0.44       100
weighted avg       0.79      0.69      0.57       100

[[68  0]
 [31  1]]


#NB Bernoli


In [ ]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print ("Accuracy : ", 
accuracy_score(y_test,y_pred)*100) 
	
print("Report : ", 
classification_report(y_test, y_pred)) 

cm2 = confusion_matrix(y_test, y_pred)
print(cm2)

Accuracy :  36.0
Report :                precision    recall  f1-score   support

           0       0.53      0.53      0.53        68
           1       0.00      0.00      0.00        32

    accuracy                           0.36       100
   macro avg       0.26      0.26      0.26       100
weighted avg       0.36      0.36      0.36       100

[[36 32]
 [32  0]]
